SELECT LAST_NAME,SALARY FROM EMPLOYEES WHERE SALARY>12000;


--3
SELECT LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY NOT BETWEEN 5000 AND 12000;


--4
SELECT LAST_NAME, JOB_ID, HIRE_DATE FROM EMPLOYEES WHERE LAST_NAME = 'Matos' OR LAST_NAME = 'Taylor';

--5
SELECT LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID=20 OR DEPARTMENT_ID=50 ORDER BY LAST_NAME ASC;

--6
SELECT LAST_NAME AS "EMPLOYEE", SALARY AS "MONTHLY SALARY" FROM EMPLOYEES
WHERE (SALARY BETWEEN 5000 AND 12000) AND (DEPARTMENT_ID=20 OR DEPARTMENT_ID=50);

--7
SELECT * FROM EMPLOYEES;
SELECT LAST_NAME, HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE = '07/06/94';

--8
SELECT * FROM EMPLOYEES;
SELECT LAST_NAME, JOB_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL;


--9
SELECT LAST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES ORDER BY SALARY DESC,COMMISSION_PCT DESC;


--10
SELECT LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY > &SALARIOPORTECLADO;

--11
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES WHERE MANAGER_ID = &INTRODUCCIRMANAGER;


--12
SELECT LAST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE '__a%';

--13

SELECT LAST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE '%a%' AND LAST_NAME LIKE '%e%';


--14
SELECT * FROM EMPLOYEES;
SELECT LAST_NAME, JOB_ID, SALARY FROM EMPLOYEES WHERE (JOB_ID = 'SA_REP' OR JOB_ID='ST_CLERK')
AND (SALARY <> 2500 OR SALARY <> 3500 OR SALARY <> 7000);



--15

SELECT LAST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES WHERE COMMISSION_PCT = 0.2;