SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_NAME LIKE '%ing';


SELECT JOB_TITLE,MIN_SALARY, MAX_SALARY, (MAX_SALARY - MIN_SALARY)
AS "VARIANCE"
FROM JOBS WHERE JOB_TITLE LIKE '%President%' OR JOB_TITLE LIKE '%Manager%' ORDER BY 
"VARIANCE" DESC, JOB_TITLE DESC;


SELECT * FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, (SALARY*12) AS "ANUAL SALARY", &&TAX_RATE AS "TAX RATE",(&TAX_RATE*SALARY*12) AS TAX
FROM EMPLOYEES WHERE EMPLOYEE_ID = &EMPLOYEE_ID;

UNDEFINE TAX_RATE;