SELECT ROUND(AVG(LENGTH(COUNTRY_NAME)),0) AVERAGE_COUNTRY_NAME_LENGTH FROM COUNTRIES;


SELECT * FROM JOB_HISTORY;

SELECT TO_CHAR(END_DATE,'YYYY') AS "Quitting year", JOB_ID, COUNT(*) AS "Number of employees"
FROM JOB_HISTORY GROUP BY END_DATE, JOB_ID ORDER BY 3 DESC;


SELECT TO_CHAR(HIRE_DATE, 'DAY'), COUNT(*) FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE,'DAY') 
HAVING COUNT(*) >= 15;