--4
SELECT * FROM EMPLOYEES;

SELECT ROUND(MAX(SALARY),0) Maximium,ROUND(MIN(SALARY),0) Minimium, ROUND(SUM(SALARY),0) SUM, ROUND(AVG(SALARY),0) AVERAGE FROM EMPLOYEES;


--5
SELECT JOB_ID, ROUND(MAX(SALARY),0) Maximium,ROUND(MIN(SALARY),0) Minimium, ROUND(SUM(SALARY),0) SUM, ROUND(AVG(SALARY),0) AVERAGE 
FROM EMPLOYEES
GROUP BY JOB_ID;
