SELECT 'The job id for' || ' ' || FIRST_NAME || ' ' ||'is' || ' ' ||JOB_ID AS "EMPLOYEE DETSAILS" FROM EMPLOYEES;


--5

SELECT * FROM EMPLOYEES;

SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME = 'king';


SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE LOWER(LAST_NAME) = 'king';


--6
SELECT EMPLOYEE_ID, CONCAT(FIRST_NAME, LAST_NAME) NAME, LENGTH(LAST_NAME), INSTR(LAST_NAME, 'a') "Containts'a'?"
FROM EMPLOYEES WHERE LAST_NAME LIKE '%n';

SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '%n';


--7
SELECT * FROM EMPLOYEES;

SELECT INITCAP(21/7)FROM DUAL;
SELECT INITCAP(SYSDATE)FROM DUAL;
SELECT INITCAP('init cap or init_cap or init%cap')FROM DUAL;


--8
SELECT * FROM COUNTRIES;


SELECT * FROM COUNTRIES WHERE LENGTH(COUNTRY_NAME) >= 10;



--9

SELECT LPAD(1000+200.55,14,'*') FROM DUAL;
SELECT RPAD(1000+200.55,14,'*') FROM DUAL;
SELECT LPAD(SYSDATE, 14, '$#') FROM DUAL;
SELECT RPAD(SYSDATE, 14, '$#') FROM DUAL; 


--10


SELECT TRIM(trailing 'e' from 1+2.14||'is pie') from dual;
SELECT TRIM(both '*' from '*******Hidden*******') from dual;
SELECT TRIM(1 FROM SYSDATE) FROM DUAL;


--11
SELECT REPLACE('1#3#5#7#9', '#','->') FROM DUAL;


SELECT REPLACE('1#3#5#7#9', '#') FROM DUAL;


--12

SELECT ROUND(1601.916718, 1) FROM DUAL;
SELECT ROUND(1601.916718, 2) FROM DUAL;
SELECT ROUND(1601.916718, -3) FROM DUAL;
SELECT ROUND(1601.916718) FROM DUAL;


--13

SELECT TRUNC(1601.916718, 1) FROM DUAL;
SELECT TRUNC(1601.916718, 2) FROM DUAL;
SELECT TRUNC(1601.916718, -3) FROM DUAL;
SELECT TRUNC(1601.916718) FROM DUAL;




--14
SELECT MOD(6,2) FROM DUAL;
SELECT MOD(5,3) FROM DUAL;
SELECT MOD(7,35) FROM DUAL;
SELECT MOD(5.2,3) FROM DUAL;






--16

SELECT * FROM EMPLOYEES;


SELECT EMPLOYEE_ID, HIRE_DATE, ADD_MONTHS(HIRE_DATE,6) AS "REVIEW", NEXT_DAY(HIRE_DATE,5) AS "NEXT_DAY", LAST_DAY(HIRE_DATE) AS "LAST_DAY" FROM EMPLOYEES;


--17
SELECT EMPLOYEE_ID, HIRE_DATE, ROUND(HIRE_DATE,'MONTH') AS "ROUND(HIRE_DATE, MONTH)", TRUNC(HIRE_DATE, 'MONTH') AS "TRUNC(HIRE_DATE MONTH)" FROM EMPLOYEES;






























