SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'MM/YY') AS MONTH_HIRED FROM EMPLOYEES;


--SCC
SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'CC') AS DATESSCC FROM EMPLOYEES;

--YYYY
SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'MM/YYYY') AS DATESYYYY FROM EMPLOYEES;

--IYYY, IYYY, IYY, I
SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'IYYY') AS DATESIYYY FROM EMPLOYEES;
SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'IYY') AS DATESIYY FROM EMPLOYEES;
SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'IY') AS DATESIY FROM EMPLOYEES;
SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'I') AS DATESI FROM EMPLOYEES;

--BC
SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'YYYYBC') AS DATEBC FROM EMPLOYEES;

SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'B.C') AS DATEBC FROM EMPLOYEES;

--Q
SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,QUARTER) AS DATEQ FROM EMPLOYEES;


--RM
SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'DDD') AS DATEQ FROM EMPLOYEES;


--DAY
SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'DAY-MM-YYYY') AS DATEQ FROM EMPLOYEES;

--DY
SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'DY') AS DATEQ FROM EMPLOYEES;



--J
SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'J') AS DATEJ FROM EMPLOYEES;

--IW
SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'IW') AS DATEW FROM EMPLOYEES;


--2DA PARTE

SELECT LAST_NAME, TO_CHAR(HIRE_DATE,'ddspth DD HH12:00:00 AM') AS HIRE_DATE FROM EMPLOYEES;



SELECT LAST_NAME, TO_CHAR(HIRE_DATE,'ddspth' || ' ' || '"OF" Month' || ' ' ||'YYYY' || ' ' ||'HH12:MI:SS AM') AS HIRE_DATE FROM EMPLOYEES;


--6
SELECT LAST_NAME, HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE = TO_DATE ('May 24, 1999', 'fxMonth DD, YYYY');



--7
SELECT TO_CHAR(SYSDATE, '"Hoy es"' || 'DD'  || ' ' || '"de" Month' || '"del"' ||'YYYY' || '"y son las"' || ' ' ||'HH:MI:SS AM') AS FECHA FROM DUAL;



--8
SELECT EMPLOYEE_ID,HIRE_DATE, NEXT_DAY(HIRE_DATE, 'FRIDAY') NEXT_FRIDAY FROM EMPLOYEES;
SELECT EMPLOYEE_ID,HIRE_DATE FROM EMPLOYEES;


--10

SELECT last_name, salary, commission_pct, ROUND(SALARY+(SALARY*COMMISSION_PCT)) AS NEW_SALARY FROM employees;

SELECT * FROM EMPLOYEES;


--11
SELECT LAST_NAME, SALARY,
DECODE(SALARY,
SALARY<=1999, 0.0*SALARY,
(SALARY >= 2000 AND SALARY<=3999, 0.09* SALARY),
(SALARY>= 4000 AND SALARY<=5999, 0.20* SALARY),
(SALARY>=6000 AND SALARY <=7999, 0.30*SALARY),
(SALARY >=8000 AND SALARY <= 9999, 0.40*SALARY),
(SALARY >=10000 AND SALARY <=11999, 0.42*SALARY),
(SALARY >=122000 AND SALARY <=13999, 0.44*SALARY),
(SALARY >= 14000, 0.45*SALARY),
SALARY)
TAX_RATE FROM EMPLOYEES;


--12
SALARY_LOW = 5000;


SELECT EMPLOYEE_ID, LAST_NAME, SALARY,
CASE SALARY WHEN SALARY(SALARY <=5000) THEN "SALARIO_BAJO"
WHEN SALARY(SALARY >= 5000 AND SALARY >= 10000) THEN "SALARIO_MEDIO"
WHEN SALARY(SALARY >10000) THEN "SALARIO_ALTO"
ELSE SALARY END
FROM EMPLOYEES;



