--1
SELECT * FROM HOTEL_CATEGORIA;
SELECT * FROM RESERVA;

SELECT * FROM RESERVA WHERE PRECIO = '$1000 p/noche' ;

--2
SELECT * FROM AGENCIA;

SELECT * FROM AGENCIA WHERE ID_AGENCIA > 1 AND ID_AGENCIA< 5;

--3
SELECT * FROM HOTEL;

SELECT * FROM HOTEL WHERE ID_HOTEL >= 1 AND ID_HOTEL<= 4; 

--4

SELECT * FROM RESERVA;
SELECT * FROM RESERVA WHERE FECHA_FIN BETWEEN '12/09/21' AND '20/09/21';



SELECT * FROM HOTEL ;

SELECT * FROM HOTEL WHERE FECHA_CONSTRUCCION NOT BETWEEN '18/09/15' AND '17/08/2018'; 
--5
SELECT * FROM HABITACION WHERE NOMBRE_HABITACION IN('Habitacion Queen');

SELECT * FROM HABITACION WHERE NOMBRE_HABITACION NOT IN('Habitacion Queen');

--6
SELECT * FROM CLIENTE;
SELECT * FROM CLIENTE WHERE APPATERNO_CLIENTE LIKE '%Morales%';

--7
SELECT * FROM HOTEL_CATEGORIA;
SELECT * FROM HOTEL_CATEGORIA WHERE ESTRELLAS IS NOT NULL;
--8
SELECT * FROM EMPLEADO;
SELECT * FROM EMPLEADO WHERE APPATERNO_EMPLEADO = 'Castro' AND APMATERNO_EMPLEADO = 'Almeida';
--9
SELECT * FROM HABITACION;
SELECT * FROM HABITACION WHERE ID_HABITACION = 1 OR ID_HABITACION =2;
--10

--11

--12

--13
SELECT * FROM AGENCIA;
SELECT * FROM AGENCIA WHERE NOMBRE_AGENCIA='&NOMBRE_AGENCIA';

--14
SELECT * FROM EMPLEADO ORDER BY APPATERNO_EMPLEADO ASC;

--15
SELECT * FROM EMPLEADO;

