--TABLAS DE ENTIDADES

CREATE TABLE AGENCIA(
ID_AGENCIA NUMBER(6) CONSTRAINT ID_AAGENCIA_NN NOT NULL,
TELEFONO_AGENCIA VARCHAR(10),
NOMBRE_AGENCIA VARCHAR2(15),
DOMICILIO_AGENCIA VARCHAR2(50)
);

CREATE TABLE EMPLEADO(
ID_EMPLEADO NUMBER(6),
TELEFONO_EMPLEADO VARCHAR2(10),
NOMBRE_EMPLEADO VARCHAR2(15),
APPATERNO_EMPLEADO VARCHAR2(20),
APMATERNO_EMPLEADO VARCHAR2(20)
);


CREATE TABLE CLIENTE(
ID_CLIENTE NUMBER(6),
NOMBRE_CLIENTE VARCHAR2(25),
APPATERNO_CLIENTE VARCHAR2(25),
APMATERNO_CLIENTE VARCHAR2(25),
TELEFONO_CLIENTE VARCHAR2(10),
DOMICILIO_CLIENTE VARCHAR(60)
);

CREATE TABLE HABITACION(
ID_HABITACION NUMBER(6),
NOMBRE_HABITACION VARCHAR2(25)
);

CREATE TABLE TIPO_HABITACION(
ID_TIPO_HABITACION NUMBER(6),
DESCRIPCION VARCHAR2(35)
);

CREATE TABLE HOTEL(
ID_HOTEL NUMBER(6),
FECHA_CONSTRUCCION DATE,
NOMBRE_HOTEL VARCHAR2(25),
TELEFONO VARCHAR2(10),
DOMICILIO VARCHAR2(50)
);

 
CREATE TABLE CATEGORIA(
ID_CATEGORIA NUMBER(6),
IVA CHAR(4),
DESCRIPCION VARCHAR2(25)
);

--TABLAS PROCESOS

CREATE TABLE AGENCIA_EMPLEO(
ID_AGENCIA NUMBER(6),
ID_EMPLEADO NUMBER(6)
);

CREATE TABLE RESERVA(
ID_RESERVA NUMBER(6),
FECHA_INICIO DATE,
PRECIO VARCHAR2(15),
FECHA_FIN DATE,
ID_CLIENTE NUMBER(6),
ID_EMPLEADO NUMBER(6)
);

CREATE TABLE HOTEL_CATEGORIA(
ID_CATEGORIA NUMBER(6),
ID_HOTEL NUMBER(6)
);

CREATE TABLE HABITACION_TIPOHABITACION(
ID_TIPO NUMBER(6),
ID_HABITACION NUMBER(6)
);

CREATE TABLE HABITACION_HOTEL(
ID_HOTEL NUMBER(6),
ID_HABITACION NUMBER(6),
CANTIDAD_HABITACIONES VARCHAR2(25)
);








