--TABLAS DE ENTIDADES
/*TABLA DE AGENCIA*/
CREATE TABLE AGENCIA(
ID_AGENCIA NUMBER(6) CONSTRAINT ID_AAGENCIA_NN NOT NULL,
TELEFONO_AGENCIA VARCHAR(10),
NOMBRE_AGENCIA VARCHAR2(15),
DOMICILIO_AGENCIA VARCHAR2(50)
);
--Creando llaves con el ALTER TABLE
ALTER TABLE AGENCIA ADD CONSTRAINT AGENCIA_ID_PK PRIMARY KEY(ID_AGENCIA);
--*****************************************************************************----
/*TABLA DE EMPLEADO*/
CREATE TABLE EMPLEADO(
ID_EMPLEADO NUMBER(6) CONSTRAINT ID_EMPLEADO_NN NOT NULL,
TELEFONO_EMPLEADO VARCHAR2(10),
NOMBRE_EMPLEADO VARCHAR2(15),
APPATERNO_EMPLEADO VARCHAR2(20),
APMATERNO_EMPLEADO VARCHAR2(20)
);
--Creando llaves con el ALTER TABLE
ALTER TABLE EMPLEADO ADD CONSTRAINT EMPLEADO_ID_PK PRIMARY KEY(ID_EMPLEADO);
--*****************************************************************************----
/*TABLA DE CLIENTE*/
CREATE TABLE CLIENTE(
ID_CLIENTE NUMBER(6) CONSTRAINT ID_CLIENTE_NN NOT NULL,
NOMBRE_CLIENTE VARCHAR2(25),
APPATERNO_CLIENTE VARCHAR2(25),
APMATERNO_CLIENTE VARCHAR2(25),
TELEFONO_CLIENTE VARCHAR2(10),
DOMICILIO_CLIENTE VARCHAR(60)
);
--Creando llaves con el ALTER TABLE
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_ID_PK PRIMARY KEY(ID_CLIENTE);
--*****************************************************************************----
/*TABLA DE HABITACION*/
CREATE TABLE HABITACION(
ID_HABITACION NUMBER(6),
NOMBRE_HABITACION VARCHAR2(25)
);

--Creando llaves con el ALTER TABLE
ALTER TABLE HABITACION ADD CONSTRAINT HABITACION_ID_PK PRIMARY KEY(ID_HABITACION);
--*****************************************************************************----
/*TABLA DE TIPO DE HABITACION*/
CREATE TABLE TIPO_HABITACION(
ID_TIPO_HABITACION NUMBER(6),
DESCRIPCION VARCHAR2(35)
);

--Creando llaves con el ALTER TABLE
ALTER TABLE TIPO_HABITACION ADD CONSTRAINT TH_ID_PK PRIMARY KEY(ID_TIPO_HABITACION);

--*****************************************************************************----
/*TABLA DE HOTEL*/
CREATE TABLE HOTEL(
ID_HOTEL NUMBER(6),
FECHA_CONSTRUCCION DATE,
NOMBRE_HOTEL VARCHAR2(25),
TELEFONO VARCHAR2(10),
DOMICILIO VARCHAR2(50)
);

--Creando llaves con el ALTER TABLE
ALTER TABLE HOTEL ADD CONSTRAINT HOTEL_ID_PK PRIMARY KEY(ID_HOTEL);

--*****************************************************************************----
/*TABLA DE CATEGORIA*/
 
CREATE TABLE CATEGORIA(
ID_CATEGORIA NUMBER(6),
IVA CHAR(4),
DESCRIPCION VARCHAR2(25)
);

--Creando llaves con el ALTER TABLE
ALTER TABLE CATEGORIA ADD CONSTRAINT CATEGORIA_ID_PK PRIMARY KEY(ID_CATEGORIA);
--*****************************************************************************----
/*TABLA DE AGENCIA_EMPLEO*/
CREATE TABLE AGENCIA_EMPLEO(
ID_AGENCIA NUMBER(6),
ID_EMPLEADO NUMBER(6)
);

--Creando llaves con el ALTER TABLE
ALTER TABLE AGENCIA_EMPLEO ADD CONSTRAINT AGENCIA_EMPLEADO_PK PRIMARY KEY(ID_AGENCIA);
--CREAMOS ALTER DE LLAVES FORANEAS
ALTER TABLE AGENCIA_EMPLEO ADD CONSTRAINT AGENCIA_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO);


--*****************************************************************************----
/*TABLA DE RESERVA*/
CREATE TABLE RESERVA(
ID_RESERVA NUMBER(6),
FECHA_INICIO DATE,
PRECIO VARCHAR2(15),
FECHA_FIN DATE,
ID_CLIENTE NUMBER(6),
ID_EMPLEADO NUMBER(6)
);


--Creando llaves con el ALTER TABLE
ALTER TABLE RESERVA ADD CONSTRAINT ID_RESERVA_PK PRIMARY KEY(ID_RESERVA);
--CREAMOS ALTER DE LLAVES FORANEAS
ALTER TABLE RESERVA ADD CONSTRAINT CLIENTE_RESERVA FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);
ALTER TABLE RESERVA ADD CONSTRAINT EMPLEADO_RESERVA FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO);


--*****************************************************************************----
/*TABLA DE HOTEL_CATEGORIA*/
CREATE TABLE HOTEL_CATEGORIA(
ID_CATEGORIA NUMBER(6),
ID_HOTEL NUMBER(6)
);

--CREAMOS ALTER DE LLAVES FORANEAS
ALTER TABLE HOTEL_CATEGORIA ADD CONSTRAINT HOTEL_CATEGORIA_FK FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA);

ALTER TABLE HOTEL_CATEGORIA ADD CONSTRAINT HOTEL_CATEGORIA_H_FK FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL(ID_HOTEL);


--*****************************************************************************----
/*TABLA DE HABITACION TIPO HABITACION*/

CREATE TABLE HABITACION_TIPOHABITACION(
ID_TIPO NUMBER(6),
ID_HABITACION NUMBER(6)
);

--CREAMOS ALTER DE LLAVES FORANEAS

--Creando llaves con el ALTER TABLE
ALTER TABLE HABITACION_TIPOHABITACION ADD CONSTRAINT ID_TIPO_PK PRIMARY KEY(ID_TIPO);
ALTER TABLE HABITACION_TIPOHABITACION ADD CONSTRAINT TIPO_HAB_FK FOREIGN KEY (ID_HABITACION) REFERENCES HABITACION(ID_HABITACION);

--*****************************************************************************----
/*TABLA DE HABITACION TIPO HABITACION*/
CREATE TABLE HABITACION_HOTEL(
ID_HOTEL NUMBER(6),
ID_HABITACION NUMBER(6),
CANTIDAD_HABITACIONES VARCHAR2(25)
);

--CREAMOS ALTER DE LLAVES FORANEAS
ALTER TABLE HABITACION_HOTEL ADD CONSTRAINT H_HAB_HOTEL_FK FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL(ID_HOTEL);
ALTER TABLE HABITACION_HOTEL ADD CONSTRAINT H_HAB_HAB FOREIGN KEY (ID_HABITACION) REFERENCES HABITACION(ID_HABITACION);






