CREATE TABLE EMP AS
SELECT EMPLOYEE_ID EMPNO, LAST_NAME ENAME, DEPARTMENT_ID DEPTNO FROM EMPLOYEES;

CREATE TABLE DEPT AS SELECT DEPARTMENT_ID DEPTNO, DEPARTMENT_NAME DNAME FROM DEPARTMENTS;

DESCRIBE EMP;
DESCRIBE DEPT;

ALTER TABLE EMP ADD CONSTRAINT EMP_PK PRIMARY KEY(EMPNO);
ALTER TABLE DEPT ADD CONSTRAINT DEPT_PK PRIMARY KEY(DEPTNO);

ALTER TABLE EMP ADD CONSTRAINT DEPT_FK FOREIGN KEY(DEPTNO) REFERENCES DEPT ON DELETE SET NULL;


INSERT INTO DEPT VALUES(10,'NEW DEPARTMENT');
INSERT INTO EMP VALUES(9999,'NEW EMP',99);
TRUNCATE TABLE DEPT;

DROP TABLE EMP;
DROP TABLE DEPT;