---ACTIVIDAD 4

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE LOWER(FIRST_NAME)LIKE '%li%';

--2
SELECT FIRST_NAME, LAST_NAME, CONCAT(SUBSTR(FIRST_NAME,1,1),SUBSTR(LAST_NAME,1,14)) AS "FORMAL NAME"
FROM EMPLOYEES WHERE(LENGTH(FIRST_NAME)+ LENGTH(LAST_NAME)) > 15;


--3
SELECT EMPLOYEE_ID, LAST_NAME, HIRE_DATE, MONTHS_BETWEEN(HIRE_DATE, '01-01-2000') AS "MONTHS WORKED"
FROM EMPLOYEES WHERE MONTHS_BETWEEN(HIRE_DATE, '01-01-2000') > 90;

--4
SELECT CONCAT(FIRST_NAME, LAST_NAME) AS "NAME AND LAST NAME", LENGTH(LAST_NAME) AS "LENGTH LAST NAME",
INSTR(LAST_NAME,'a') AS "POSITION OF LETTER A" FROM EMPLOYEES WHERE SUBSTR(LAST_NAME, -1,1) = 'n';

--5
SELECT EMPLOYEE_ID, HIRE_DATE, ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE),3) AS "MONTHS EMPLOYEED", ADD_MONTHS(HIRE_DATE,6) AS "SIX MONTHS REVIEW",
NEXT_DAY(HIRE_DATE,'VIERNES') AS "FIRST FRIDAY", LAST_DAY(HIRE_DATE) AS "LAST DAY OF HIRE MONTH" FROM EMPLOYEES WHERE MONTHS_BETWEEN(SYSDATE,HIRE_DATE)<150; 


--6
SELECT EMPLOYEE_ID, HIRE_DATE FROM EMPLOYEES WHERE SUBSTR(HIRE_DATE,-2,2)='03';








--ACTIVIDAD FINAL
--1
SELECT CURRENT_DATE FROM DUAL;

--2
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, ROUND((SALARY*15.5),2) AS "NEW SALARY" FROM EMPLOYEES;



--3
