DESCRIBE DEPARTAMENTOS_DAMC;
DESCRIBE EMPLEADOS_DAMC;
DESCRIBE HISTORIA_LABORAL_DAMC;
DESCRIBE LOCALIZACION_DAMC;
DESCRIBE PAISES_DAMC;
DESCRIBE REGIONES_DAMC;
DESCRIBE TRABAJOS_DAMC;

--SEQUENCIAS
CREATE SEQUENCE SEQUENCE_REGIONES_ID
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 9999
    MINVALUE 1
    NOCYCLE 
    NOCACHE ;
    
    
CREATE SEQUENCE SEQUENCE_LOCALIZACION_ID
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 9999
    MINVALUE 1
    NOCYCLE 
    NOCACHE ;
    
    
CREATE SEQUENCE SEQUENCE_DEPARTAMENTO_ID
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 9999
    MINVALUE 1
    NOCYCLE 
    NOCACHE ;
    
 
CREATE SEQUENCE SEQUENCE_EMPLEADO_ID
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 9999
    MINVALUE 1
    NOCYCLE 
    NOCACHE ;
    
--Sinonimos  
    
 CREATE SYNONYM DEPTS_DAMC FOR DEPARTAMENTOS_DAMC;
 CREATE SYNONYM EMPS_DAMC FOR EMPLEADOS_DAMC;
 CREATE SYNONYM HL_DAMC FOR HISTORIA_LABORAL_DAMC;
 CREATE SYNONYM LOC_DAMC FOR LOCALIZACION_DAMC;
 CREATE SYNONYM PA_DAMC FOR PAISES_DAMC;
 CREATE SYNONYM REG_DAMC FOR REGIONES_DAMC;
 CREATE SYNONYM TRA_DAMC FOR TRABAJOS_DAMC;
    
    
    
--INDEX
--TABLA DEPARTAMENTOS_DAMC
CREATE INDEX NOM_DEPT_IDX ON DEPARTAMENTOS_DAMC(NOMBRE_DEPARTAMENTO);
CREATE INDEX GERENTE_DEPT_IDX ON DEPARTAMENTOS_DAMC(GERENTE_ID);
CREATE INDEX LOCALIZACION_DEPT_IDX ON DEPARTAMENTOS_DAMC(LOCALIZACION_ID);

--TABLA EMPLEADOS_dAMC
CREATE INDEX NOM_EMP_IDX ON EMPLEADOS_DAMC(NOMBRE_EMPLEADO);
CREATE INDEX AP_EMP_IDX ON EMPLEADOS_DAMC(APELLIDO_EMPLEADO);
CREATE INDEX TRA_EMP_IDX ON EMPLEADOS_DAMC(TRABAJO_ID);
CREATE INDEX SALARIO_EMP_IDX ON EMPLEADOS_DAMC(SALARIO);
CREATE INDEX GER_EMP_IDX ON EMPLEADOS_DAMC(GERENTE_ID);
CREATE INDEX DEPT_EMP_IDX ON EMPLEADOS_DAMC(DEPARTAMENTO_ID);


--TABLA HISTORIA_LABORAL_DAMC
CREATE INDEX HL_FECHA_INICIO_IDX ON HISTORIA_LABORAL_DAMC(FECHA_INICIO);
CREATE INDEX HL_FECHA_FINAL_IDX ON HISTORIA_LABORAL_DAMC(FECHA_FINAL);
CREATE INDEX TRA_HL_IDX ON HISTORIA_LABORAL_DAMC(TRABAJO_ID);
CREATE INDEX DEPT_HL_IDX ON HISTORIA_LABORAL_DAMC(DEPARTAMENTO_ID);
    
    
--TABLA LOCALIZACION_DAMC
CREATE INDEX LOC_CP_IDX ON LOCALIZACION_DAMC(CODIGO_POSTAL);
CREATE INDEX CIUD_LOC_IDX ON LOCALIZACION_DAMC(CIUDAD);
CREATE INDEX EST_PRO_LOC_IDX ON LOCALIZACION_DAMC(ESTADO_PROVINCIA);
CREATE INDEX PAI_LOC_IDX ON LOCALIZACION_DAMC(PAIS_ID);
    
--TABLA PAISES_DAMC
CREATE INDEX NOM_PAI_IDX ON PAISES_DAMC(NOMBRE_PAIS);
CREATE INDEX REG_PAI_IDX ON PAISES_DAMC(REGION_ID);


--TABLA REGIONES_DAMC

CREATE INDEX NOM_REG_IDX ON REGIONES_DAMC(NOMBRE_REGION);

--TABLA TRABAJOS_DAMC
CREATE INDEX TIT_TRA_IDX ON TRABAJOS_DAMC(TITULO_TRABAJO);


    
    
    
    
    