DESCRIBE AGENCIA;
DESCRIBE AGENCIA_EMPLEO;
DESCRIBE CATEGORIA;
DESCRIBE CLIENTE;
DESCRIBE EMPLEADO;
DESCRIBE HABITACION;
DESCRIBE HABITACION_HOTEL;
DESCRIBE HABITACION_TIPOHABITACION;
DESCRIBE HOTEL;
DESCRIBE HOTEL_CATEGORIA;
DESCRIBE RESERVA;
DESCRIBE TIPO_HABITACION;

--SEQUENCIAS
CREATE SEQUENCE SEQUENCE_AGENCIA_ID
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 50
    MINVALUE 1
    NOCYCLE 
    NOCACHE ;
    
    
CREATE SEQUENCE SEQUENCE_AGENCIA_EMPLEO_ID
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 50
    MINVALUE 1
    NOCYCLE 
    NOCACHE ;
    
    
CREATE SEQUENCE SEQUENCE_CATEGORIA_ID
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 50
    MINVALUE 1
    NOCYCLE 
    NOCACHE ;
    
 
CREATE SEQUENCE SEQUENCE_CLIENTE_ID
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 9999
    MINVALUE 1
    NOCYCLE 
    NOCACHE ;
    
 
CREATE SEQUENCE SEQUENCE_EMPLEADO_ID
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 200
    MINVALUE 1
    NOCYCLE 
    NOCACHE ;
  
  
CREATE SEQUENCE SEQUENCE_HABITACION_ID
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 150
    MINVALUE 1
    NOCYCLE 
    NOCACHE ;
    

CREATE SEQUENCE SEQUENCE_HABITACION_HOTEL_ID
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 150
    MINVALUE 1
    NOCYCLE 
    NOCACHE ;
 

CREATE SEQUENCE SEQUENCE_HABITACION_TIPOHABITACION_ID
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 10
    MINVALUE 1
    NOCYCLE 
    NOCACHE ;     
    

CREATE SEQUENCE SEQUENCE_HOTEL_ID
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 100
    MINVALUE 1
    NOCYCLE 
    NOCACHE ;
    
CREATE SEQUENCE SEQUENCE_HOTEL_CATEGORIA_ID
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 5
    MINVALUE 1
    NOCYCLE 
    NOCACHE ;
    
    
CREATE SEQUENCE SEQUENCE_RESERVA_ID
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 9999
    MINVALUE 1
    NOCYCLE 
    NOCACHE ;    
 
CREATE SEQUENCE SEQUENCE_TIPO_HABITACION_ID
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 9999
    MINVALUE 1
    NOCYCLE 
    NOCACHE ;    
       
    
--SINONIMOS  
    
 CREATE SYNONYM AGEN FOR AGENCIA;
 CREATE SYNONYM AGEN_EMP FOR AGENCIA_EMPLEO;
 CREATE SYNONYM CAT FOR CATEGORIA;
 CREATE SYNONYM CLIEN FOR CLIENTE;
 CREATE SYNONYM EMP FOR EMPLEADO;
 CREATE SYNONYM HABIT FOR HABITACION;
 CREATE SYNONYM HABIT_HOT FOR HABITACION_HOTEL;
 CREATE SYNONYM HABIT_TH FOR HABITACION_TIPOHABITACION;
 CREATE SYNONYM HOT FOR HOTEL;
 CREATE SYNONYM HOT_CAT FOR HOTEL_CATEGORIA;
 CREATE SYNONYM RES FOR RESRVA;
 CREATE SYNONYM T_H FOR TIPO_HABITACION;
    

--INDEX
--TABLA AGENCIA
CREATE INDEX AGEN_NOMBRE_IDX ON AGENCIA(NOMBRE_AGENCIA);

--TABLA AGENCIA_EMPLPEO
CREATE INDEX ID_AGENCIA_EMP_IDX ON AGENCIA_EMPLEO(ID_EMPLEADO);


--TABLA CLIENTE
CREATE INDEX NOM_CLIE_IDX ON CLIENTE(NOMBRE_CLIENTE);
CREATE INDEX APPATERNO_CLIE_IDX ON CLIENTE(APPATERNO_CLIENTE);
CREATE INDEX APMATERNO_CLIE_IDX ON CLIENTE(APMATERNO_CLIENTE);

--TABLA EMPLEADO
CREATE INDEX NOM_CLIE_IDX ON CLIENTE(NOMBRE_EMPLEADO);
CREATE INDEX APPATERNO_EMPL_IDX ON CLIENTE(APPATERNO_EMPLEADO);
CREATE INDEX APMATERNO_EMPL_IDX ON CLIENTE(APMATERNO_EMPLEADO);

--TABLA HABITACION
CREATE INDEX NOM_HABIT_IDX ON HABITACION(NOMBRE_HABITACION);


--TABLA HABITACION_HOTEL
CREATE INDEX ID_HABIT_IDX ON HABITACION_HOTEL(ID_HABITACION);

--TABLA HABITACION_TIPOHABITACION
CREATE INDEX ID_HABIT_TH_IDX ON HABITACION_TIPOHABITACION(ID_HABITACION);


--TABLA HOTEL
CREATE INDEX NOM_HOTEL_IDX ON HOTEL(NOMBRE_HOTEL);


--TABLA HOTEL_CATEGORIA
CREATE INDEX ID_HOT_IDX ON HOTEL_CATEGORIA(HOTEL_CATEGORIA);

--TABLA RESERVA 
CREATE INDEX FECHA_INICIO_IDX ON RESERVA(FECHA_INICIO);
CREATE INDEX FECHA_FIN_IDX ON RESERVA(FECHA_FIN);
CREATE INDEX FECHA_CLIENTE_IDX ON RESERVA(ID_CLIENTE);
CREATE INDEX FECHA_EMPLEADO_IDX ON RESERVA(ID_EMPLEADO);


