

--actividad 3

SELECT PRODUCT_NAME, CATALOG_URL, SUBSTR(CATALOG_URL, 17,6) AS "SUPPLIER NUMBER" FROM
PRODUCT_INFORMATION WHERE LOWER(PRODUCT_DESCRIPTION) LIKE '%color%' AND LOWER(PRODUCT_DESCRIPTION) LIKE '%printer%';