/*ESTABLISHEMNT TABLE*/
CREATE TABLE ESTABLISHMENT_P4(
ESTABLISHMENT_ID NUMBER,
NAME_ESTABLISHMENT VARCHAR2(25) CONSTRAINT NAME_ESTABLISHMENT_NN NOT NULL
);

--ALTER PRIMARY  KEY
ALTER TABLE ESTABLISHMENT_P4 ADD CONSTRAINT EST_ID_PK PRIMARY KEY(ESTABLISHMENT_ID);


/*PRODUCT TABLE*/
CREATE TABLE PRODUCT_P4(
PRODUCT_ID NUMBER CONSTRAINT PRODUCT_ID_UNIQUE UNIQUE,
AUTHOR VARCHAR2(25),
TITLE_PRODUCT VARCHAR(25),
PRICE_PRODUCT VARCHAR(25)
);
--ALTER PRIMARY  KEY
ALTER TABLE PRODUCT_P4 ADD CONSTRAINT PROD_ID_PK PRIMARY KEY(PRODUCT_ID);

/*WAREHOUSE TABLE*/
CREATE TABLE WAREHOUE_P4(
WAREHOUSE_ID NUMBER,
NAME_WAREHOUSE VARCHAR2(25),
ADDRESS_WAREHOUSE VARCHAR2(50)
);
--ALTER PRIMARY  KEY
ALTER TABLE WAREHOUSE_P4 ADD CONSTRAINT WAREHOUSE_ID_PK PRIMARY KEY(WAREHOUSE_ID);

/*CUSTOMER TABLE*/
CREATE TABLE CUSTOMER_P4(
CUSTOMER_ID NUMBER,
NAME_CUSTOMER VARCHAR2(25),
FIRST_LAST_NAME VARCHAR2(25),
SECOND_LAST_NAME VARCHAR2(25),
EMAIL VARCHAR2(50)
);

--ALTER PRIMARY  KEY
ALTER TABLE CUSTOMER_P4 ADD CONSTRAINT CUST_ID_PK PRIMARY KEY(CUSTOMER_ID);

--PROCESS
/*SHOPPINGCART TABLE*/
CREATE TABLE SHOPPINGCART_P4(
CUSTOMER_ID NUMBER,
PRODUCT_ID NUMBER
);
--ALTER PRIMARY  KEY
ALTER TABLE SHOPPINGCART_P4 ADD CONSTRAINT CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
ALTER TABLE SHOPPINGCART_P4 ADD CONSTRAINT PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);


/*PURCHASE TABLE*/
CREATE TABLE PURCHASE_P4(
PURCHASE_NUMBER NUMBER,
DATE_PURCHASE DATE,
CUSTOMER_ID NUMBER,
PRODUCT_ID NUMBER,
ESTABLISHMENT_ID NUMBER
);
--ALTER FOREING  KEY
ALTER TABLE PURCHASE_P4 ADD CONSTRAINT CUST_PURCH_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
ALTER TABLE PURCHASE_P4 ADD CONSTRAINT PROD_PURCH_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);
ALTER TABLE PURCHASE_P4 ADD CONSTRAINT ESTA_PURCH_FK FOREIGN KEY (ESTABLISHMENT_ID) REFERENCES ESTABLISHMENT(ESTABLISHMENT_ID);


/*STORED TABLE*/
CREATE TABLE STORED_P4(
PRODUCT_ID NUMBER,
WAREHOUSE_ID NUMBER
);
--ALTER FOREIGN  KEY
ALTER TABLE STORED_P4 ADD CONSTRAINT PROD_S_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);
ALTER TABLE STORED_P4 ADD CONSTRAINT WARE_S_FK FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID);



--Index
CREATE INDEX ESTABLISH_P4__INDX ON ESTABLISHMENT_P4(NAME_ESTABLISHMENT);
CREATE INDEX PURCH_P4__INDX ON PURCHASE_P4(PURCHASE_NUMBER);



--SEQUENCE
CREATE SEQUENCE SEQUENCE_ESTABLISHMENT_ID
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 5
    CYCLE;

CREATE SEQUENCE SEQUENCE_PRODUCT_ID
    INCREMENT BY 1
    START WITH 1;

CREATE SEQUENCE SEQUENCE_WAREHOUSE_ID
    INCREMENT BY 1
    START WITH 1
    ORDER;
    
CREATE SEQUENCE SEQUENCE_CUSTOMER_ID
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 1000
    CYCLE;



--SYNONYMS
CREATE SYNONYM P4_EST FOR ESTABLISHMENT_P4;
CREATE SYNONYM P4_PROD FOR PRODUCT_P4;
CREATE SYNONYM P4_WH FOR WAREHOUSE_P4;
CREATE SYNONYM P4_CUST FOR CUSTOMER_P4;
CREATE SYNONYM P4_SC FOR SHOPPINGCART_P4;
CREATE SYNONYM P4_PURCH FOR PURCHASE_P4;
CREATE SYNONYM P4_STO FOR STORED_P4;



--ACT7_4

CREATE TABLE REF_TEMPLATE_TYPES(
TEMPLATE_TYPE_CODE CHAR(15),
TEMPLATE_TYPE_DESCRIPTION VARCHAR2(255)
);

--ALTER PRIMARY  KEY
ALTER TABLE REF_TEMPLATES_TYPES ADD CONSTRAINT TEMPLATE_TYPE_CODE PRIMARY KEY(TEMPLATE_TYPE_CODE);

CREATE TABLE TEMPLATES(
TEMPLATE_ID NUMBER,
VERSION_NUMBER NUMBER,
TEMPLATE_TYPE_CODE CHAR(15),
DATE_EFFECTIVE_FROM DATE,
DATE_EFFECTIVE_TO DATE,
TEMPLATE_DETAILS VARCHAR2(255)
);

--ALTER PRIMARY  KEY
ALTER TABLE TEMPLATES ADD CONSTRAINT TEMPLATE_ID_PK PRIMARY KEY(TEMPLATE_ID);
--ALTER FOREIGN  KEY
ALTER TABLE TEMPLATES ADD CONSTRAINT T_T_C_FK FOREIGN KEY (TEMPLATE_TYPE_CODE) REFERENCES REF_TEMPLATE_TYPES(TEMPLATE_TYPE_CODE);


CREATE TABLE DOCUMENTS(
DOCUMENT_ID NUMBER,
TEMPLATE_ID NUMBER,
DOCUMENT_NAME VARCHAR2(255),
DOCUMENT_DESCRIPTION VARCHAR2(255),
OTHER_DETAILS VARCHAR2(255)
);
--ALTER PRIMARY  KEY
ALTER TABLE DOCUMENTS ADD CONSTRAINT DOCUMENT_ID_PK PRIMARY KEY(DOCUMNET_ID);
--ALTER FOREIGN  KEY
ALTER TABLE DOCUMENTS ADD CONSTRAINT DOC_TEM_FK FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATES(TEMPLATE_ID);




CREATE TABLE PARAGRAPHS(
PARAGRAPH_ID NUMBER,
DOCUMENT_ID NUMBER,
PARAGRAPH_TEXT VARCHAR2(255),
OTHER_DETAILS VARCHAR2(255)
);

--ALTER PRIMARY  KEY
ALTER TABLE PARAGRAPHS ADD CONSTRAINT PARAGRAPH_ID_PK PRIMARY KEY(PARAGRAPH_ID);

--ALTER FOREIGN  KEY
ALTER TABLE PARAGRAPHS ADD CONSTRAINT D_P_FK FOREIGN KEY (PARAGRAPH_ID) REFERENCES PARAGRAPHS(PARAGRAPH_ID);


--Index
CREATE INDEX TEMPLATES_INDX ON TEMPLATES(VERSION_NUMBER);
CREATE INDEX DOCUMENT_INDX ON DOCUMENTS(DOCUMENT_NAME);



--SEQUENCE
CREATE SEQUENCE SEQUENCE_TEMPLATES_ID
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 5
    CYCLE;

CREATE SEQUENCE SEQUENCE_DOCUMENTS_ID
    INCREMENT BY 1
    START WITH 1;

CREATE SEQUENCE SEQUENCE_PARAGRAPHS_ID
    INCREMENT BY 1
    START WITH 1
    ORDER;
    

--SYNONYMS
CREATE SYNONYM TEMP FOR TEMPLATES;
CREATE SYNONYM REF_T_TY FOR REF_TEMPLATE_TYPE;
CREATE SYNONYM DOCS FOR DOCUMENTS;
CREATE SYNONYM PHAR FOR PARAGRAPHS;





























































