/*VEHICLE TABLE*/
CREATE TABLE P4_VEHICLE(
ID_VEH NUMBER,
LIC_PLATES VARCHAR2(10) ,
OWNER_ID NUMBER
);

--ALTER TABLE FOR KEYS
--PRIMARY KEY
ALTER TABLE P4_VEHICLE ADD CONSTRAINT ID_VEH_PK PRIMARY KEY(ID_VEH);
--FOREIGN KEY
ALTER TABLE P4_VEHICLE ADD CONSTRAINT OWN_VEH_ID_FK FOREIGN KEY(OWNER_ID) REFERENCES P4_OWNER(OWNER_ID);

/*OWNER TABLE*/
CREATE TABLE P4_OWNER(
OWNER_ID NUMBER,
SURNAME VARCHAR2(10),
FORENAME VARCHAR2(10),
DATEOBIRTH DATE
);
--PRIMARY KEY
ALTER TABLE P4_OWNER ADD CONSTRAINT ID_OWNER_PK PRIMARY KEY(OWNER_ID);

--INDEX
CREATE INDEX P4_VEH_INDX ON P4_VEHICLE(LIC_PLATES);
--INDEX
CREATE INDEX P4_OWN_INDX ON P4_OWNER(SURNAME,FORENAME);
