/*CHANNEL TABLE*/
CREATE TABLE P4_CHANNEL(
CHANNEL_ID NUMBER(4),
CNAME VARCHAR2(25)
);

--ALTERSFOR CREATE CONSTRAINTS OF PRIMARY KEYS
ALTER TABLE P4_CHANNEL ADD CONSTRAINT CHANNEL_ID_PK PRIMARY KEY(CHANNEL_ID);

/*EMPLOYEE TABLE*/
CREATE TABLE P4_EMPLOYEE(
EMP_ID NUMBER(4),
EMP_NAME VARCHAR2(25),
EMP_LASTN VARCHAR2(25),
BOSS_ID NUMBER(4),
ADDRESS VARCHAR2(50),
DATE_OF_BIRTH DATE,
GENDER VARCHAR2(15),
BENEFICIARIES VARCHAR2(25)
);
--ALTERSFOR CREATE CONSTRAINTS OF PRIMARY KEYS

ALTER TABLE P4_EMPLOYEE ADD CONSTRAINT EMPLOYEE_ID_PK PRIMARY KEY(EMP_ID);


/*PRODUCT TABLE*/
CREATE TABLE P4_PRODUCT(
PRODUCT_ID NUMBER(4),
PNAME VARCHAR2(25),
SALE_PRICE VARCHAR2(25),
PURCHASE_PRICE VARCHAR2(25),
PROVIDER VARCHAR2(25)
);
--ALTERS FOR CREATE CONSTRAINTS OF PRIMARY KEYS
ALTER TABLE P4_PRODUCT ADD CONSTRAINT PRODUCT_ID_PK PRIMARY KEY(PRODUCT_ID);



CREATE TABLE P4_SHOP(
SHOP_ID NUMBER(4),
ADDRESS VARCHAR2(25),
MANAGER_SHOP VARCHAR2(25)
);
--ALTERSFOR CREATE CONSTRAINTS OF PRIMARY KEYS
ALTER TABLE P4_SHOP ADD CONSTRAINT SHOP_ID_PK PRIMARY KEY(SHOP_ID);


/*SALES TABLE*/
CREATE TABLE P4_SALES(
SALE_ID NUMBER(4),
CHANNEL_ID NUMBER(4),
PRODUCT_ID NUMBER(4),
SHOP_ID NUMBER(4),
QUANTITY VARCHAR2(25),
EMP_ID NUMBER(4),
SALE_DATE DATE
);

--ALTERS FOR CREATE CONSTRAINTS OF PRIMARY KEYS
ALTER TABLE P4_SALES ADD CONSTRAINT SALES_ID_PK PRIMARY KEY(SALE_ID);

--ALTERSFOR CREATE CONSTRAINTS OF FOREIGN KEYS 
ALTER TABLE P4_SALES ADD CONSTRAINT CHANNEL_ID_FK FOREIGN KEY (CHANNEL_ID) REFERENCES P4_CHANNEL(CHANNEL_ID);
ALTER TABLE P4_SALES ADD CONSTRAINT PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES P4_PRODUCT(PRODUCT_ID);
ALTER TABLE P4_SALES ADD CONSTRAINT SHOP_ID_FK FOREIGN KEY (SHOP_ID) REFERENCES P4_SHOP(SHOP_ID);
ALTER TABLE P4_SALES ADD CONSTRAINT EMP_ID_FK FOREIGN KEY (EMP_ID) REFERENCES P4_EMPLOYEE(EMP_ID);


--CREATE INDEX AND SYNONYMS
 CREATE INDEX P4_EMP_NOM_INDX ON P4_EMPLOYEE(EMP_NAME);
 CREATE INDEX P4_PRO_NAM_INDX ON P4_PRODUCT(PNAME);
 
 
 
  CREATE SEQUENCE SEQUENCE_SALE_ID
    INCREMENT BY 1
    START WITH 1;
 

 CREATE SEQUENCE SEQUENCE_CHANNEL_ID
    INCREMENT BY 1
    START WITH 1;

 CREATE SEQUENCE SEQUENCE_PRODUCT_ID
    INCREMENT BY 1
    START WITH 1;
 

CREATE SEQUENCE SEQUENCE_SHOP_ID
    INCREMENT BY 1
    START WITH 1;
 
CREATE SEQUENCE SEQUENCE_EMPLOYEE_ID
    INCREMENT BY 1
    START WITH 1;



CREATE SYNONYM P6_CH FOR P6_CHANNEL;
CREATE SYNONYM P6_EMP FOR P6_EMPLOYEE;
CREATE SYNONYM P6_PROD FOR P6_PRODUCT;
CREATE SYNONYM P6_SH FOR P6_SHOP;
CREATE SYNONYM P6_S FOR P6_SALES;






