DESCRIBE PRODUCT_INFORMATION;
DESCRIBE ORDERS;

SELECT UNIQUE SALES_REP_ID FROM ORDERS;


SELECT ORDER_ID, ORDER_DATE, ORDER_TOTAL FROM ORDERS;
SELECT * FROM HR.JOB_HISTORY;


SELECT PRODUCT_NAME || 'WITH CODE:' || PRODUCT_ID || 'HAS STATUS OF:' || PRODUCT_STATUS AS "PRODUCT", LIST_PRICE, MIN_PRICE, LIST_PRICE - MIN_PRICE
    AS "MAXIM ACTUAL SAVINGS",((LIST_PRICE - MIN_PRICE)/LIST_PRICE)*100 AS "MAX % DESCOUNT" FROM PRODUCT_INFORMATION;
    

SELECT 4*(22/7)*(3958.759*3958.759) AS "E AAREA" FROM DUAL;

