SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;


SELECT REGION_ID FROM  REGIONS WHERE REGION_NAME = 'Europe';
SELECT COUNTRY_NAME, REGION_ID FROM COUNTRIES WHERE REGION_ID=1;


DESCRIBE JOBS;
DESCRIBE JOB_HISTORY;
DESCRIBE LOCATIONS;
DESCRIBE COUNTRIES;
DESCRIBE REGIONS;


SELECT EMPLOYEE_ID, JOB_ID, START_DATE, END_DATE,((1+(END_DATE-START_DATE))/365.25) AS "YEARS EMPLOYEED" FROM JOB_HISTORY;


SELECT 'THE JOB ID FOR:' || JOB_TITLE || '''S JOB IS' || JOB_ID AS "JOB DESC" FROM JOBS;

SELECT (22/7)*(6000*6000) AS "AREA" FROM DUAL;


SELECT LAST_NAME, JOB_ID, SALARY AS SAL FROM EMPLOYEES;

SELECT * FROM JOBGRADES;

SELECT EMPLOYEE_ID, LAST_NAME SALX12 ANNUAL SALARY;


DESCRIBE DEPARTMENTS;
SELECT * FROM DEPARTMENTS;


DESCRIBE EMPLOYEES;


--ACTIVIDAD 5
SELECT LAST_NAME || ',' || JOB_ID AS "EMPLOYEE AND TITLE" FROM EMPLOYEES;


SELECT EMPLOYEE_ID || ',' || FIRST_NAME  || ',' || LAST_NAME || ',' || EMAIL || ',' || PHONE_NUMBER || ',' || HIRE_DATE || ',' || JOB_ID || ',' || SALARY || ',' || COMMISSION_PCT || ',' ||
MANAGER_ID || ',' || DEPARTMENT_ID
AS "THE OUTPUT" FROM EMPLOYEES;








