--practica 3 actividad 3

CREATE TABLE CUSTOMER(
    CUSTOMER_NUMBER NUMBER(10) CONSTRAINT CUSTOMER_NUMBER_PK PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(25) CONSTRAINT CUSTOMER_NAME_NN NOT NULL,
    LAST_NAME VARCHAR(25) CONSTRAINT LAST_NAME_NN NOT NULL,
    DATE_BIRTHDAY DATE,
    CUSTOMER_ADDRESS VARCHAR(60),
    CUSTOMER_RFC VARCHAR(18) CONSTRAINT  CUSTOMER_RFC_NN NOT NULL,
    TELEPHONE_NUMBER NUMBER(10),
    CONSTRAINT TEL_CUS_FK FOREIGN KEY(TELEPHONE_NUMBER) REFERENCES TELEPHONE(TELEPHONE_NUMBER)
);


CREATE TABLE TELEPHONE(
TELEPHONE_NUMBER NUMBER(10) CONSTRAINT TELEPHONE_PK PRIMARY KEY,
ACTIVATIION_DATE DATE,
FLAG CHAR(1),
BRAND VARCHAR2(30),
PHONE_CAPACITY VARCHAR2(50),
SERIAL_NUMBER NUMBER(8)
);


