CREATE TABLE PRODUCT_HIERARCHY (
    PRODUCT_CODE NUMBER(4) CONSTRAINT PRODUCT_CODE_NN NOT NULL,
    PARENT_PRODUCT_CODE NUMBER(4) CONSTRAINT PARENT_PRODUCT_CODE_NN NOT NULL,
    PRODUCT_NAME VARCHAR2(25),
    PRODUCT_DESCRIPTION VARCHAR2(25),
    AMOUNT_REQUIRED NUMBER(4)
);



CREATE TABLE PPRODUCT_SUPPLIERS(
    PRODUCT_CODE NUMBER(4) CONSTRAINT PRODUCT_CODE_SUPPLIERS_NN NOT NULL ,
    SUPPLIER_CODE NUMBER(4)CONSTRAINT SUPPLIER_CODE_NN NOT NULL,
    SUPPLIED_FROM_DATE DATE,
    SUPPLIED_TO_DATE DATE
);




CREATE TABLE SUPPLIERS(
SUPPLIER_CODE NUMBER(4),
SUPPLIER_DETAILS VARCHAR2(25)
);



ALTER TABLE SUPPLIERS ADD STATUS NUMERIC(4);
ALTER TABLE SUPPLIERS ADD NAME_SUPPLIER VARCHAR(25);
ALTER TABLE SUPPLIERS ADD CITY INT;

ALTER TABLE SUPPLIERS DROP COLUMN STATUS;

ALTER TABLE SUPPLIERS RENAME COLUMN CITY TO CITY_ADDRESS;


ALTER TABLE SUPPLIERS MODIFY(CITY_ADDRESS VARCHAR(50));

DESCRIBE SUPPLIERS;


ALTER TABLE PRODUCT_HIERARCHY ADD CONSTRAINT PRODUCT_CODE_PK PRIMARY KEY (PRODUCT_CODE);
DESCRIBE PRODUCT_HIERARCHY;


ALTER TABLE PRODUCT_HIERARCHY ADD CONSTRAINT PARENT_PRODUCT_CODE_FK FOREIGN KEY (PARENT_PRODUCT_CODE) REFERENCES PRODUCT_HIERARCHY(PARENT_PRODUCT_CODE);


ALTER TABLE SUPPLIERS ADD CONSTRAINT SUPPLIER_CODE_PK PRIMARY KEY(SUPPLIER_CODE);

ALTER TABLE PPRODUCT_SUPPLIERS ADD CONSTRAINT PRODUCT_CODE_FK FOREIGN KEY(PRODUCT_CODE) REFERENCES PRODUCT_HIERARCHY(PRODUCT_CODE);
ALTER TABLE PPRODUCT_SUPPLIERS ADD CONSTRAINT SUPPLIER_CODE_FK FOREIGN KEY(SUPPLIER_CODE) REFERENCES SUPPLIERS(SUPPLIER_CODE);

ALTER TABLE PRODUCT_HIERARCHY ADD CONSTRAINT PARENT_PRODUCT_CODE_FK FOREIGN KEY(PARENT_PRODUCT_CODE) REFERENCES PRODUCT_HIERARCHY(PARENT_PRODUCT_CODE);



--ACTIVIDAD 7

CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID NUMBER(4) CONSTRAINT EMPLOYEE_ID_NN NOT NULL,
    START_DATE DATE,
    DESCRIPTION_JOB VARCHAR2(25),
    STATUS VARCHAR(25),
    FIRST_NAME VARCHAR(25),
    LAST_NAME  VARCHAR(25)
);

CREATE TABLE JOB(
    ID_JOB NUMBER(4) CONSTRAINT ID_JOB__NN NOT NULL,
    ID_EMPLOYEE NUMBER(4) CONSTRAINT ID_EMPLOYEE_NN NOT NULL,
    JOB_NAME VARCHAR(25),
    JOB_DESCRIPTION VARCHAR2(25)
);


CREATE TABLE BRANCH(
ID_BRANCH NUMBER(4),
NAME_BRANCH VARCHAR2(25),
ID_EMPLOYEE NUMBER(4),
ID_JOB NUMBER(4),
ID_MANAGER NUMBER(4)
);



CREATE TABLE MANAGER(
    ID_MANAGER NUMBER(4),
    FIRST_NAME VARCHAR(25),
    LAST_NAME VARCHAR2(25)
);





ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_ID_PK PRIMARY KEY (EMPLOYEE_ID);
ALTER TABLE JOB ADD CONSTRAINT JOB_ID_PK PRIMARY KEY (ID_JOB);
ALTER TABLE BRANCH ADD CONSTRAINT BRANCH_ID_PK PRIMARY KEY (ID_BRANCH);
ALTER TABLE MANAGER ADD CONSTRAINT MANAGER_ID_PK PRIMARY KEY (ID_MANAGER);


ALTER TABLE JOB ADD CONSTRAINT ID_EMPLOYE_FK FOREIGN KEY(ID_EMPLOYEE) REFERENCES EMPLOYEE(ID_EMPLOYEE);
ALTER TABLE BRANCH ADD CONSTRAINT ID_EMPLOYEE_FK FOREIGN KEY (ID_EMPLOYEE)  REFERENCES EMPLOYEE(EMPLOYEE_ID);
ALTER TABLE BRANCH ADD CONSTRAINT ID_JOB_FK FOREIGN KEY(ID_JOB) REFERENCES JOB(ID_JOB);
ALTER TABLE BRANCH ADD CONSTRAINT ID_MANAGER_FK FOREIGN KEY(ID_MANAGER) REFERENCES MANAGER(ID_MANAGER);





--Index
CREATE INDEX EMPLOYEE_INDX ON EMPLOYEE(FIRST_NAME,LAST_NAME);
CREATE INDEX JOB_INDX ON JOB(JOB_NAME);
CREATE INDEX MANAGER_INDX ON MANAGER(FIRST_NAME,LAST_NAME);


--SEQUENCE
CREATE SEQUENCE SEQUENCE_EMPLOYEE_ID
    INCREMENT BY 1
    START WITH 1;

CREATE SEQUENCE SEQUENCE_JOB_ID
    INCREMENT BY 1
    START WITH 1;
    
CREATE SEQUENCE SEQUENCE_BRANCH_ID
    INCREMENT BY 1
    START WITH 1;

CREATE SEQUENCE SEQUENCE_MANAGER_ID
    INCREMENT BY 1
    START WITH 1;
    

--SYNONYMS
CREATE SYNONYM EMPL FOR EMPLOYEE;
CREATE SYNONYM JB FOR JOB;
CREATE SYNONYM BR FOR BRANCH;
CREATE SYNONYM MGER FOR MANAGER;
















DROP TABLE BRANCH;
DROP TABLE EMPLOYEE;
DROP TABLE JOB;
DROP TABLE MANAGER;
DROP TABLE PPRODUCT_SUPPLIERS;
DROP TABLE PRODUCT_HIERARCHY;
DROP TABLE SUPPLIERS;

--ACTIVIDAD 8

CREATE TABLE CUSTOMER(
CUSTOMER_ID NUMBER(4),
CUSTOMER_NAME VARCHAR2(25),
CUSTOMER_FIRST_LAST_NAME VARCHAR2(25),
CUSTOMER_SECOND_LAST_NAME VARCHAR2(25),
CUSTOMER_ADDRESS VARCHAR2(50),
CUSTOMER_EMAIL VARCHAR2(50),
CUSTOMER_PHONE_NUMBER VARCHAR2(10)
);


CREATE TABLE BRANCH(
BRANCH_ID NUMBER(4),
BRANCH_NAME VARCHAR(25),
BRANCH_ADDRESS VARCHAR2(25),
ASSETS VARCHAR2(26)
);


CREATE TABLE LOAN_BRANCH(
BRANCH_ID NUMBER(4),
LOAN_ID NUMBER(4)
);


CREATE TABLE LOAN(
LOAN_ID NUMBER(4),
LOAN_NUMBER VARCHAR2(25),
AMOUNT VARCHAR(25)
);


CREATE TABLE CUST_BANKER(
TYPE_CUST VARCHAR2(25),
CUSTOMER_ID NUMBER(4),
ACCOUNT_NUMBER VARCHAR2(25)
);

CREATE TABLE EMPLOYEE(
EMPLOYE_ID NUMBER(4),
DEPENDENT_NAME VARCHAR2(25),
PHONE_NUMBER VARCHAR2(10),
EMPLOYEE_NAME VARCHAR2(25),
EMPLOYEMEENT_LENGTH CHAR(8),
START_DATE DATE,
CUST_BANKER_TYPE VARCHAR2(25),
EMPLOYEE_EMPLOYEE_ID NUMBER(4)
);


CREATE TABLE DEPOSITOR(
ACCESS_DATE DATE,
CUSTOMER_ID NUMBER(4),
ACCOUNT_NUMBER CHAR(8)
);

CREATE TABLE BORROWER(
CUSTOMER_ID NUMBER(4),
LOAN_ID NUMBER(4)
);


CREATE TABLE LOAN_PAYMENT(
LOAN_ID NUMBER(4),
PAYMENT_ID NUMBER(4)
);


CREATE TABLE PAYMENT(
PAYMENT_ID NUMBER(4),
PAYMENT_NUMBER CHAR(8),
PAYMENT_DATE DATE,
PAYMENT_ACCOUNT VARCHAR2(25)
);

CREATE TABLE ACCOUNT_BRANCH(
BRANCH_ID NUMBER(4),
ACCOUNT_NUMBER CHAR(8)
);

CREATE TABLE ACCOUNT(
ACCOUNT_NUMBER CHAR(8),
BALANCE VARCHAR2(25)
);


CREATE TABLE SAVINGS_ACCOUNT(
INTERES_RATE CHAR(6),
CHECKING_RATE CHAR(10),
ACCOUNT_NUMBER CHAR(8)
);


CREATE TABLE CHECKING_ACCOUNT(
OVERDFRAFT_AMOUNT VARCHAR2(16),
ACCOUNT_NUMBER CHAR(8)
);



ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_ID_PK PRIMARY KEY(CUSTOMER_ID);
ALTER TABLE BRANCH ADD CONSTRAINT BRANCH_ID_PK PRIMARY KEY(BRANCH_ID);
ALTER TABLE LOAN ADD CONSTRAINT LOAN_ID_PK PRIMARY KEY(LOAN_ID);
ALTER TABLE CUST_BANKER ADD CONSTRAINT CUST_BANKER_ID_PK PRIMARY KEY(TYPE_CUST);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_ID_PK PRIMARY KEY(EMPLOYE_ID);
ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_ID_PK PRIMARY KEY(PAYMENT_ID);
ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_ID_PK PRIMARY KEY(ACCOUNT_NUMBER);


ALTER TABLE CUST_BANKER ADD CONSTRAINT CUSTOMER_ID_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
ALTER TABLE EMPLOYEE ADD CONSTRAINT CUST_BANKER_TYPE_ID_FK FOREIGN KEY(CUST_BANKER_TYPE) REFERENCES CUST_BANKER(TYPE_CUST);
ALTER TABLE LOAN_BRANCH ADD CONSTRAINT BRANCH_ID_FK FOREIGN KEY(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID);
ALTER TABLE LOAN_BRANCH ADD CONSTRAINT LOAN_ID_FK FOREIGN KEY(LOAN_ID) REFERENCES LOAN(LOAN_ID);
ALTER TABLE BORROWER ADD CONSTRAINT CUSTOMER_ID_BORROWER_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
ALTER TABLE BORROWER ADD CONSTRAINT LOAN_ID_BORROWER_FK FOREIGN KEY(LOAN_ID) REFERENCES LOAN(LOAN_ID);
ALTER TABLE LOAN_PAYMENT ADD CONSTRAINT LOAN_ID_PAYMENT_FK FOREIGN KEY(LOAN_ID) REFERENCES LOAN(LOAN_ID);
ALTER TABLE LOAN_PAYMENT ADD CONSTRAINT PAYMENT_ID_PAYMENT_FK FOREIGN KEY(PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID);
ALTER TABLE DEPOSITOR ADD CONSTRAINT CUSTOMER_DEPOSITOR_ID_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
ALTER TABLE DEPOSITOR ADD CONSTRAINT ACCOUNT_DEPOSITOR_ID_FK FOREIGN KEY(ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NUMBER);
ALTER TABLE SAVINGS_ACCOUNT ADD CONSTRAINT SAVING_ACCOUNT_ID_FK FOREIGN KEY(ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NUMBER);
ALTER TABLE CHECKING_ACCOUNT ADD CONSTRAINT CHECKING_ACCOUNT_ID_FK FOREIGN KEY(ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NUMBER);

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_EMPLOYEE_ID_FK FOREIGN KEY(EMPLOYE_ID) REFERENCES EMPLOYEE(EMPLOYE_ID);

ALTER TABLE ACCOUNT_BRANCH ADD CONSTRAINT BRANCH_ACCOUNT_ID FOREIGN KEY(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID);
ALTER TABLE ACCOUNT_BRANCH ADD CONSTRAINT ACCOUNT_NUMBER_BRANCH_ID FOREIGN KEY(ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NUMBER);









































