CREATE TABLE ESTABLISHMENT(
    ESTABLISHEMNT_ID NUMBER(4),
    NAME_ESTABLISHMENT VARCHAR2(8),
    CONSTRAINT ESTABLISHMENT_ID_PK PRIMARY KEY(establishmentID)
);

CREATE TABLE PRODUCT(
    PRODUCT_ID NUMBER(4),
    AUTHOR VARCHAR2(8),
    TITLE VARCHAR2(16),
    PRICE_PRODUCT NUMBER(8),
    CONSTRAINT PRODUCT_PK PRIMARY KEY(PRODUCT_ID)
);

CREATE TABLE WAREHOUSE(
    WAREHOUSE_ID NUMBER(4),
    NAME_WAREHOUSE VARCHAR2(16),
    ADDRESS_WAREHOUSE VARCHAR2(16),
    CONSTRAINT WAREHOUSE_PK PRIMARY KEY(WAREHOUSE_ID)
);

CREATE TABLE CUSTOMER(
    CUSTOMER_ID NUMBER(4),
    NAME_CUSTOMER VARCHAR2(8),
    FIRST_LAST_NAME VARCHAR2(16),
    SECOND_LAST_NAME VARCHAR2(16),
    EMAIL_CUSTOMER VARCHAR2(30),
    CONSTRAINT CUSTOMER_PK PRIMARY KEY(CUSTOMER_ID)
);


CREATE TABLE BLUE_RAY(
    NAME_BLUE_RAY VARCHAR(16),
    DURATION_BLUE_RAY VARCHAR(16)
);

CREATE TABLE MUSICAL_MEDIUM(
    GENDER VARCHAR2(16),
    KIND VARCHAR2(16)
);

CREATE TABLE ELECTRONIC_CARDS(
    PRICE VARCHAR(16)
);

CREATE TABLE BOOK(
    GENDER VARCHAR(8),
    PUBLISHER VARCHAR(16),
    EDITION_BOOK VARCHAR(8)
);

/*Procesos*/

CREATE TABLE PURCHASE(
    PURCHASE_NUMBER CHAR(4),
    DATE_PURCHASE Date,
    CUSTOMER_ID NUMBER(4),
    PRODUCT_ID NUMBER(4),
    ESTABLISHMENT_ID NUMBER(4),
    
    
    CONSTRAINT PURCHASE_NUMBER_PK PRIMARY KEY(PURCHASE_NUMBER,DATE_PURCHASE,CUSTOMER_ID,PRODUCT_ID,ESTABLISHMENT_ID),
    CONSTRAINT CUSTOMER_ID_PURCHASE FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    CONSTRAINT PRODUCT_ID_PURCHASE FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT ESTABLISHMENT_ID_PURCHASE FOREIGN KEY (ESTABLISHMENT_ID) REFERENCES ESTABLISHMENT(ESTABLISHMENT_ID)
);


CREATE TABLE SHOPPING_CART(
    CUSTOMER_ID NUMBER(4),
    PRODUCT_ID NUMBER(4),
    
    CONSTRAINT CUSTOMER_ID_SHOPPING_CART FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    CONSTRAINT PRODUCT_ID_SHOPPING_CART FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);


CREATE TABLE STORED(
    PRODUCT_ID NUMBER(4),
    WAREHOUSE_ID NUMBER(4),
    
    
    CONSTRAINT PRODUCT_ID_PURCHASE FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT WAREHOUSE_ID_STORED FOREIGN KEY(WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID)
);







