--(aa) Pasar los datos de las 7 tablas del esquema HR al esquema RH.

INSERT INTO REGIONES_DAMC SELECT * FROM HR.REGIONS;

INSERT INTO LOCALIZACION_DAMC SELECT * FROM HR.LOCATIONS;

INSERT INTO PAISES_DAMC SELECT * FROM HR.COUNTRIES;

INSERT INTO TRABAJOS_DAMC(TRABAJO_ID, TITULO_TRABAJO, SALARIO_MIN, SALARIO_MAX) 
    SELECT JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY FROM HR.JOBS;

INSERT INTO DEPARTAMENTOS_DAMC(DEPARTAMENTO_ID, NOMBRE_DEPARTAMENTO, LOCALIZACION_ID) 
    SELECT DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID FROM HR.DEPARTMENTS;
    
INSERT INTO EMPLEADOS_DAMC(EMPLEADO_ID, NOMBRE_EMPLEADO, APELLIDO_EMPLEADO, CORREO_ELECTRONICO,NUMERO_TELEFONO,FECHA_CONTRATACION,TRABAJO_ID,SALARIO,COMISION_PCT,DEPARTAMENTO_ID) 
    SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,DEPARTMENT_ID FROM HR.EMPLOYEES;
    
INSERT INTO HISTORIA_LABORAL_DAMC(EMPLEADO_ID,FECHA_INICIO, FECHA_FINAL, TRABAJO_ID, DEPARTAMENTO_ID) 
    SELECT EMPLOYEE_ID, START_DATE, END_DATE,JOB_ID,DEPARTMENT_ID FROM HR.JOB_HISTORY;
    
    
SELECT * FROM REGIONES_DAMC;
SELECT * FROM HR.REGIONS;
--REGIONES SI

SELECT * FROM LOCALIZACION_DAMC;
SELECT  * FROM HR.LOCATIONS;
--LOCALIZACIONES SI

SELECT * FROM TRABAJOS_DAMC;
SELECT * FROM HR.JOBS;
--TRABAJOS SI
SELECT * FROM PAISES_DAMC;
SELECT * FROM HR.COUNTRIES;
--PAISES SI
SELECT * FROM HISTORIA_LABORAL_DAMC;
SELECT * FROM HR.JOB_HISTORY;
--HISTORIA LABORAL NO

SELECT * FROM EMPLEADOS_DAMC;
SELECT * FROM HR.EMPLOYEES;
--EMPLEADOS NO

SELECT * FROM DEPARTAMENTOS_DAMC;
SELECT * FROM HR.DEPARTMENTS;
--DEPARTAMENTOS SI PERO SIN EL MANAGER_ID -- ERRORES CONSTANTES


DESCRIBE TRABAJOS_DAMC;
DESCRIBE HR.JOBS;
DESCRIBE HISTORIA_LABORAL_DAMC;
DESCRIBE HR.JOB_HISTORY;
DESCRIBE EMPLEADOS_DAMC;
DESCRIBE HR.EMPLOYEES;
DESCRIBE DEPARTAMENTOS_DAMC;
DESCRIBE HR.DEPARTMENTS;

--b) Insertar 5 registros a cada tabla de RH haciendo uso de las secuencias elaboradas en el Capítulo 11.


--5 REGIONES
INSERT INTO REGIONES_DAMC VALUES (
SEQ_REGIONES_ID.NextVal,
'Oceania');

INSERT INTO REGIONES_DAMC VALUES (
SEQ_REGIONES_ID.NextVal,
'Latin America');

INSERT INTO REGIONES_DAMC VALUES (
SEQ_REGIONES_ID.NextVal,
'South Africa');

INSERT INTO REGIONES_DAMC VALUES (
SEQ_REGIONES_ID.NextVal,
'North Africa');

INSERT INTO REGIONES_DAMC VALUES (
SEQ_REGIONES_ID.NextVal,
'South America');



DESCRIBE LOCALIZACION_DAMC;
--5 LOCALIZACIONES
INSERT INTO LOCALIZACION_DAMC VALUES (
SEQ_LOCALIZACION_ID.NextVal,
'De la Mora', '98607','Guadalupe', 'Zacatecas', 'MX');

INSERT INTO LOCALIZACION_DAMC VALUES (
SEQ_LOCALIZACION_ID.NextVal,
'Ferrocarril', '98600','Guadalupe', 'Zacatecas', 'MX');

INSERT INTO LOCALIZACION_DAMC VALUES (
SEQ_LOCALIZACION_ID.NextVal,
'El caminito', '31662','Buenos Aires', 'Argentina', 'AR');

INSERT INTO LOCALIZACION_DAMC VALUES (
SEQ_LOCALIZACION_ID.NextVal,
'Colmar', '68000','Colmar', 'Gran Este', 'FR');


INSERT INTO LOCALIZACION_DAMC VALUES (
SEQ_LOCALIZACION_ID.NextVal,
'Isla de burano', '98600','Burano', 'Venecia', 'IT'); --ERROR A PROPOSITO PARA UPDATE

--consultar para revisar
DESCRIBE DEPARTAMENTOS_DAMC;
SELECT * FROM DEPARTAMENTOS_DAMC;
SELECT * FROM LOCALIZACION_DAMC;
--5 DEPARTAMENTOS
INSERT INTO DEPARTAMENTOS_DAMC VALUES (
SEQ_DEPARTAMENTO_ID.NextVal,'Infrastructures area',null,1500); 

INSERT INTO DEPARTAMENTOS_DAMC VALUES (
SEQ_DEPARTAMENTO_ID.NextVal,'IA Systems',null,1500); 

INSERT INTO DEPARTAMENTOS_DAMC VALUES (
SEQ_DEPARTAMENTO_ID.NextVal,'Bussiness area',null,1600); 

INSERT INTO DEPARTAMENTOS_DAMC VALUES (
SEQ_DEPARTAMENTO_ID.NextVal,'New Tecnologies',null,2500); 


INSERT INTO DEPARTAMENTOS_DAMC VALUES (
SEQ_DEPARTAMENTO_ID.NextVal,'Customer Service',null,1800); 

--5 EMPLEADOS
DESCRIBE EMPLEADOS_DAMC;
SELECT * FROM EMPLEADOS_DAMC;
SELECT * FROM DEPARTAMENTOS_DAMC;

INSERT INTO EMPLEADOS_DAMC VALUES (
SEQUENCE_EMPLEADO_ID.NextVal,'Daniel', 'Morales','amcdany@gmail.com', '492.219.0147', '15/08/1999','IT_PROG', 17000, NULL,NULL, 320);  --ERROR A PROPOSITO

INSERT INTO EMPLEADOS_DAMC VALUES (
SEQ_EMPLEADO_ID.NextVal,'Jhon', 'Cena','jhoncen@gmail.com', '650.503.9899', '02/08/2012','SH_CLERK', 10000, NULL,NULL, 320); 












