CREATE TABLE MY_EMPLOYEE(
ID_EMPLOYEE NUMBER(4) CONSTRAINT  EMP_NN NOT NULL,
LAST_NAME VARCHAR2(25),
FIRST_NAME  VARCHAR2(25),
USER_ID VARCHAR(8),
SALARY NUMBER(9,2)
);



DESCRIBE MY_EMPLOYEE;


INSERT INTO MY_EMPLOYEE(ID_EMPLOYEE,FIRST_NAME, LAST_NAME,USER_ID,SALARY)
VALUES(1,'Patel','Ralph','rpatel',895);
INSERT INTO MY_EMPLOYEE(ID_EMPLOYEE,FIRST_NAME, LAST_NAME,USER_ID,SALARY)
VALUES(2,'Dancs','Betty','bdancs',860);
INSERT INTO MY_EMPLOYEE(ID_EMPLOYEE,FIRST_NAME, LAST_NAME,USER_ID,SALARY)
VALUES(3,'Biri','Ben','bbiri',1100);
INSERT INTO MY_EMPLOYEE(ID_EMPLOYEE,FIRST_NAME, LAST_NAME,USER_ID,SALARY)
VALUES(4,'Newman','Chad','cneweman',750);
INSERT INTO MY_EMPLOYEE(ID_EMPLOYEE,FIRST_NAME, LAST_NAME,USER_ID,SALARY)
VALUES(5,'Roperburn','Audrey','aropebur',1550);


commit;

--ACT10-PARTE10
UPDATE MY_EMPLOYEE
  SET LAST_NAME='Drexler'
  WHERE ID_EMPLOYEE=3;
--11
UPDATE MY_EMPLOYEE set SALARY=1000 WHERE SALARY <
900;
--12
SELECT * FROM MY_EMPLOYEE;
  
--13,14
DELETE FROM MY_EMPLOYEE where FIRST_NAME='Dancs' AND LAST_NAME = 'Betty';
  
  
COMMIT;


--15,16,17
SELECT * FROM MY_EMPLOYEE;





DROP TABLE MY_EMPLOYEE;
  
  
  